### ISSUE TITLE
please delete a few files

### ISSUE THREAD

**Issue by sbeaulieu** [CeNCOOS/OBIS_workshop_2024_IFCB#2]
Please delete the following files which have been replaced by files with new filenames

- DwC matching to IFCB use case.xlsx
- getSantaCruzdata.ipynb

also please delete the following notebook because functions have been moved into .py scripts

- ifcb_rest_api_convert.ipynb

Note these files will still be accessible from the git history.

**Comment by flbahr** [comment]
Stace, 
Files deleted. 
Fred 


From: "Stace Beaulieu" ***@***.***> 
To: "CeNCOOS/OBIS_workshop_2024_IFCB" ***@***.***> 
Cc: "Fred Bahr" ***@***.***>, "Assign" ***@***.***> 
Sent: Monday, April 29, 2024 8:30:20 AM 
Subject: [CeNCOOS/OBIS_workshop_2024_IFCB] please delete a few files (Issue #2) 





Please delete the following files which have been replaced by files with new filenames 

    * DwC matching to IFCB use case.xlsx 
    * getSantaCruzdata.ipynb 


also please delete the following notebook because functions have been moved into .py scripts 

    * ifcb_rest_api_convert.ipynb 


Note these files will still be accessible from the git history.

**Comment by sbeaulieu** [comment]
Re-opening because I just noticed that the ole' DwC matching to IFCB use case.xlsx is still showing

**Comment by flbahr** [comment]
Stace,
I've removed the files again.  Not sure why they showed up.  Note there is only one notebook now in the notebook directory.
